*PASSWORD STRENGTH CHECKER USING ML*

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = pd.read_csv('data.csv',error_bad_lines = False)
data

Skipping line 2810: expected 2 fields, saw 5
Skipping line 4641: expected 2 fields, saw 5
Skipping line 7171: expected 2 fields, saw 5
Skipping line 11220: expected 2 fields, saw 5
Skipping line 13809: expected 2 fields, saw 5
Skipping line 14132: expected 2 fields, saw 5
Skipping line 14293: expected 2 fields, saw 5
Skipping line 14865: expected 2 fields, saw 5
Skipping line 17419: expected 2 fields, saw 5
Skipping line 22801: expected 2 fields, saw 5
Skipping line 25001: expected 2 fields, saw 5
Skipping line 26603: expected 2 fields, saw 5
Skipping line 26742: expected 2 fields, saw 5
Skipping line 29702: expected 2 fields, saw 5
Skipping line 32767: expected 2 fields, saw 5
Skipping line 32878: expected 2 fields, saw 5
Skipping line 35643: expected 2 fields, saw 5
Skipping line 36550: expected 2 fields, saw 5
Skipping line 38732: expected 2 fields, saw 5
Skipping line 40567: expected 2 fields, saw 5
Skipping line 40576: expected 2 fields, saw 5
Skipping line 41864: expected 2 field

password  strength
0           kzde5577         1
1           kino3434         1
2          visi7k1yr         1
3           megzy123         1
4        lamborghin1         1
...              ...       ...
669635    10redtux10         1
669636     infrared1         1
669637  184520socram         1
669638     marken22a         1
669639      fxx4pw4g         1

[669640 rows x 2 columns]

In [ ]:
data.head()

password  strength
0     kzde5577         1
1     kino3434         1
2    visi7k1yr         1
3     megzy123         1
4  lamborghin1         1

In [ ]:
data['strength'].unique()

array([1, 2, 0], dtype=int64)

*INSIGHTS OF DATA*

In [ ]:
data.isnull().sum()

password    1
strength    0
dtype: int64

In [ ]:
data.dropna(inplace = True)

In [ ]:
data.isnull().sum()

password    0
strength    0
dtype: int64

In [ ]:
data = np.array(data)

In [ ]:
data

array([['kzde5577', 1],
       ['kino3434', 1],
       ['visi7k1yr', 1],
       ...,
       ['184520socram', 1],
       ['marken22a', 1],
       ['fxx4pw4g', 1]], dtype=object)

*Dataset shuffling ,that makes the model to understand patterns and relationships within our dataset*.

In [ ]:
import random

In [ ]:
random.shuffle(data)

In [ ]:
ylabels  = [s[1] for s in data]
allpasswords = [s[0] for s in data]

In [ ]:
len(ylabels)

669639

In [ ]:
len(allpasswords)

669639

*Tokenization process*

In [ ]:
def createTokens(f):
    tokens = []
    for i in f:
        tokens.append(i)
    return tokens


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer = TfidfVectorizer(tokenizer=createTokens)

In [ ]:
X = vectorizer.fit_transform(allpasswords)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, ylabels, test_size=0.2, random_state=42)

*Building the model*

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf=DecisionTreeClassifier()

In [ ]:
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=clf.predict(X_test)
y_pred

array([1, 1, 1, ..., 2, 2, 1])

In [ ]:
print("Accuracy :",clf.score(X_test, y_test))

Accuracy : 0.9739188220536408


*Prediction of the data using the model*

In [ ]:
X_predict = ['drshsyqb*',
 'littledotsK18@#',
 'password##@',
 'ajd1348#28t**',
 'gtddsdsaa',
 'silasaw',
 '123456',
 'abcdef']

In [ ]:
X_predict = vectorizer.transform(X_predict)
y_Predict = clf.predict(X_predict)
print(y_Predict)

[2 2 1 2 0 0 1 0]


*From the output above, the model was able to classify the password strengths. 0 represents the weakest passwords, 1 for medium passwords, and 2 for strongest passwords.*